name: Smart Overleaf Docker Build (ARM64)

on:
  schedule:
    - cron: '0 0 * * 0'  # Ejecución semanal
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.compare.outputs.build_required }}
      new_version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get current Docker Hub version
        id: current-version
        run: |
          CURRENT=$(curl -s "https://hub.docker.com/v2/repositories/pibsas/sharelatex/tags/?page_size=1" | jq -r '.results[0].name')
          echo "CURRENT=$CURRENT" >> $GITHUB_ENV
          echo "Current Docker Hub version: $CURRENT"

      - name: Get latest toolkit version
        id: get-version
        run: |
          git clone --depth 1 https://github.com/overleaf/toolkit.git
          VERSION=$(cat toolkit/lib/config-seed/version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest toolkit version: $VERSION"

      - name: Compare versions
        id: compare
        run: |
          if [ "${{ env.CURRENT }}" != "${{ steps.get-version.outputs.version }}" ]; then
            echo "build_required=true" >> $GITHUB_OUTPUT
            echo "Version change detected (${{ env.CURRENT }} → ${{ steps.get-version.outputs.version }})"
          else
            echo "build_required=false" >> $GITHUB_OUTPUT
            echo "No version change detected"
          fi

  build:
    needs: version-check
    if: needs.version-check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Overleaf
        run: git clone --depth 1 https://github.com/overleaf/overleaf.git

      - name: Set up ARM64 environment
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push sharelatex-base
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --tag pibsas/sharelatex-base:arm64 \
            --tag pibsas/sharelatex-base:${{ needs.version-check.outputs.new_version }} \
            --tag pibsas/sharelatex-base:latest \
            --push \
            -f server-ce/Dockerfile-base \
            .

      - name: Apply Spanish packages
        run: |
          cd overleaf/server-ce
          sed -i 's|^FROM .*|FROM pibsas/sharelatex-base:arm64|' Dockerfile
          awk '/^EXPOSE/ {
              print;
              print "# Spanish language support";
              print "RUN apt-get update && apt-get install -y hunspell-es && \\";
              print "    tlmgr update --self && \\";
              print "    tlmgr install babel-spanish hyphen-spanish collection-langspanish newunicodechar float jknapltx tools collection-mathscience mathtools amsmath amsfonts enumitem cancel microtype tcolorbox && \\";
              print "    tlmgr update --all && \\";
              print "    apt-get clean && \\";
              print "    rm -rf /var/lib/apt/lists/*";
              next
          }1' Dockerfile > Dockerfile.tmp && mv Dockerfile.tmp Dockerfile

      - name: Build and push main image
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --tag pibsas/sharelatex:${{ needs.version-check.outputs.new_version }} \
            --tag pibsas/sharelatex:latest \
            -f server-ce/Dockerfile \
            .

      - name: Verify deployment
        run: |
          echo "✅ Successfully deployed version ${{ needs.version-check.outputs.new_version }}"
          echo "Docker Hub tags updated:"
          echo "- pibsas/sharelatex:${{ needs.version-check.outputs.new_version }}"
          echo "- pibsas/sharelatex:latest"
