name: Build and Push Custom Overleaf (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone Overleaf
        run: git clone --depth 1 https://github.com/overleaf/overleaf.git

      - name: Set up ARM64 build
        uses: docker/setup-qemu-action@v3

      # Configuraci칩n CORREGIDA de Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host
          install: true

      - name: Get version
        id: version
        run: |
          git clone --depth 1 https://github.com/overleaf/toolkit.git
          echo "VERSION=$(cat toolkit/lib/config-seed/version)" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cache separada para Buildx
      - name: Cache Buildx
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

      # Construcci칩n de la imagen base CON CACHE CORRECTA
      - name: Build and push sharelatex-base
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            --tag pibsas/sharelatex-base:arm64 \
            --tag pibsas/sharelatex-base:${{ env.VERSION }} \
            --tag pibsas/sharelatex-base:latest \
            --push \
            -f server-ce/Dockerfile-base \
            .
          # Mover la nueva cache a la ubicaci칩n principal
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Resto del workflow permanece igual...
      - name: Apply customizations
        run: |
          cd overleaf/server-ce
          sed -i 's|^FROM .*|FROM pibsas/sharelatex-base:arm64|' Dockerfile
          awk '/^EXPOSE/ {
              print;
              print "# Paquetes para espa침ol";
              print "RUN apt-get update && apt-get install -y hunspell-es && \\";
              print "    tlmgr update --self && \\";
              print "    tlmgr install babel-spanish hyphen-spanish collection-langspanish newunicodechar float jknapltx tools collection-mathscience mathtools amsmath amsfonts enumitem cancel microtype tcolorbox && \\";
              print "    tlmgr update --all && \\";
              print "    apt-get clean && \\";
              print "    rm -rf /var/lib/apt/lists/*";
              next
          }1' Dockerfile > Dockerfile.tmp && mv Dockerfile.tmp Dockerfile

      - name: Build and push main image
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            --push \
            --tag pibsas/sharelatex:${{ env.VERSION }} \
            --tag pibsas/sharelatex:latest \
            -f server-ce/Dockerfile \
            .
          # Actualizar cache
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
