name: Build and Push Overleaf Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo (overleaf-server)
        uses: actions/checkout@v4

      - name: Clone official overleaf repo (para Dockerfile)
        run: git clone https://github.com/overleaf/overleaf.git

      - name: Clone official overleaf-toolkit repo (para versión)
        run: git clone https://github.com/overleaf/toolkit.git

      - name: Read version file
        id: get_version
        run: echo "VERSION=$(cat toolkit/lib/config-seed/version)" >> $GITHUB_ENV

      - name: Set up QEMU for ARM builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          platforms: linux/arm64
          push: true
          tags: pibsas/sharelatex:${{ env.VERSION }}
