name: Smart Overleaf Docker Build and Upload (ARM64) for Raspberry Pi

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.compare.outputs.build_required }}
      new_version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get current RELEASE version from Docker Hub
        id: current-release
        run: |
          CURRENT_RELEASE=$(curl -s "https://hub.docker.com/v2/repositories/pibsas/sharelatex/tags/?page_size=10" | \
            jq -r '.results[] | select(.name | test("^[0-9]")) | .name' | head -1)
          echo "CURRENT_RELEASE=${CURRENT_RELEASE:-none}" >> $GITHUB_ENV
          echo "Current release version on Docker Hub: $CURRENT_RELEASE"
      
      - name: Get latest toolkit version
        id: get-version
        run: |
          git clone --depth 1 https://github.com/overleaf/toolkit.git
          VERSION=$(cat toolkit/lib/config-seed/version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest toolkit version: $VERSION"

      - name: Compare versions
        id: compare
        run: |
          if [ "${{ env.CURRENT_RELEASE }}" != "${{ steps.get-version.outputs.version }}" ]; then
            echo "build_required=true" >> $GITHUB_OUTPUT
            echo "Version change detected (${{ env.CURRENT_RELEASE }} → ${{ steps.get-version.outputs.version }})"
          else
            echo "build_required=false" >> $GITHUB_OUTPUT
            echo "No version change detected"
          fi
          
  build:
    needs: version-check
    if: needs.version-check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Overleaf
        run: git clone --depth 1 https://github.com/overleaf/overleaf.git

      - name: Set up ARM64 environment
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          driver: docker-container
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Apply Spanish packages and extra LaTeX
        run: |
          cd overleaf/server-ce
          sed -i 's/\(qpdf \)\\/\1hunspell-es \\/' Dockerfile-base
          sed -i '/^[[:space:]]*xetex[[:space:]]*\\$/a\
                babel-spanish \\ \
                hyphen-spanish \\ \
                collection-langspanish \\ \
                newunicodechar \\ \
                float \\ \
                jknapltx \\ \
                tools \\ \
                collection-mathscience \\ \
                mathtools \\ \
                amsmath \\ \
                amsfonts \\ \
                enumitem \\ \
                cancel \\ \
                microtype \\ \
                tcolorbox \\' Dockerfile-base
                
      - name: Build and push sharelatex-base
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --tag pibsas/sharelatex-base:arm64 \
            --tag pibsas/sharelatex-base:${{ needs.version-check.outputs.new_version }} \
            --tag pibsas/sharelatex-base:latest \
            --push \
            -f server-ce/Dockerfile-base \
            .

      - name: Point sharelatex Dockerfile to the recently built base image with Spanish and extra LaTeX packages
        run: |
          cd overleaf/server-ce
          sed -i 's|^FROM .*|FROM pibsas/sharelatex-base:arm64|' Dockerfile
      
      - name: Build and push main image
        run: |
          cd overleaf
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --tag pibsas/sharelatex:${{ needs.version-check.outputs.new_version }} \
            --tag pibsas/sharelatex:latest \
            -f server-ce/Dockerfile \
            .

      - name: Verify deployment
        run: |
          echo "✅ Successfully deployed version ${{ needs.version-check.outputs.new_version }}"
          echo "Docker Hub tags updated:"
          echo "- pibsas/sharelatex:${{ needs.version-check.outputs.new_version }}"
          echo "- pibsas/sharelatex:latest"
